### ISSUE TITLE
could not parse layer type PReLU?

### ISSUE THREAD

**Issue by rencheng123456** [PKUZHOU/MTCNN_TensorRT#1]
Thanks your codes.
after cmake and make ,then i run it , the result are as follows:
Beging parsing Pnet model...
could not parse layer type PReLU
End parsing Pnet model
Segmentation fault (core dumped)

I use tensorrt2.1,cudnn7.0,cuda 8.0,opencv2.4.13.
Could you tell me how to solver this problem?

**Comment by PKUZHOU** [comment]
@rencheng123456 Tensorrt don't support PReLU, I have trained a model without PReLU and has the similar performance. This project isn't finished because I am faced some problem to solve, So you can't run it properly now. I will try to finish it and provide the models latter, Thanks for your interest!

**Comment by bawdy** [comment]
Any updates on this? I'm currently facing the same issue.

**Comment by PKUZHOU** [comment]
Sorry I misplaced the prototxt, the proper one is updated

**Comment by dexception** [comment]
@PKUZHOU 
Any guidance on how to train ?
